// src/components/ProgressBar.tsx
interface ProgressBarProps {
  value: number
  showLabel?: boolean
  size?: 'sm' | 'md' | 'lg'
  className?: string
}

function getBarColor(value: number): string {
  if (value >= 80) return 'bg-emerald-500'
  if (value >= 55) return 'bg-sky-500'
  if (value >= 30) return 'bg-amber-500'
  return 'bg-red-500'
}

export default function ProgressBar({
  value,
  showLabel = true,
  size = 'md',
  className = '',
}: ProgressBarProps) {
  const clamped = Math.max(0, Math.min(100, value))
  const barColor = getBarColor(clamped)
  const heights: Record<string, string> = { sm: 'h-1.5', md: 'h-2.5', lg: 'h-3.5' }

  return (
    <div className={`w-full ${className}`}>
      {showLabel && (
        <div className="flex justify-between items-center mb-1.5">
          <span className="text-xs text-slate-400 font-medium">Overall progress</span>
          <span className="text-sm font-bold text-white">{clamped}%</span>
        </div>
      )}
      <div className={`w-full bg-slate-700 rounded-full ${heights[size]} overflow-hidden`}>
        <div
          className={`${heights[size]} rounded-full transition-all duration-500 ${barColor}`}
          style={{ width: `${clamped}%` }}
        />
      </div>
    </div>
  )
}

// src/lib/components/ProgressBar.svelte
<script lang="ts">
  let {
    value,
    showLabel = true,
    size = 'md',
  }: {
    value: number;
    showLabel?: boolean;
    size?: 'sm' | 'md' | 'lg';
  } = $props();

  const clamped = $derived(Math.max(0, Math.min(100, value)));

  const barColor = $derived(
    clamped >= 80
      ? 'bg-emerald-500'
      : clamped >= 55
        ? 'bg-sky-500'
        : clamped >= 30
          ? 'bg-amber-500'
          : 'bg-red-500'
  );

  const trackHeight = $derived(
    size === 'sm' ? 'h-1.5' : size === 'lg' ? 'h-3.5' : 'h-2.5'
  );
</script>

<div class="w-full">
  {#if showLabel}
    <div class="flex justify-between items-center mb-1.5">
      <span class="text-xs text-slate-400 font-medium">Overall progress</span>
      <span class="text-sm font-bold text-white">{clamped}%</span>
    </div>
  {/if}
  <div class="w-full bg-slate-700 rounded-full {trackHeight} overflow-hidden">
    <div
      class="{trackHeight} rounded-full transition-all duration-500 {barColor}"
      style="width: {clamped}%"
    ></div>
  </div>
</div>
